// Generated by gencpp from file serialnode/position.msg
// DO NOT EDIT!


#ifndef SERIALNODE_MESSAGE_POSITION_H
#define SERIALNODE_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serialnode
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : x()
    , y()
    , t()  {
    }
  position_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , t(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _x_type;
  _x_type x;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _y_type;
  _y_type y;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _t_type;
  _t_type t;





  typedef boost::shared_ptr< ::serialnode::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serialnode::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::serialnode::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::serialnode::position > positionPtr;
typedef boost::shared_ptr< ::serialnode::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serialnode::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serialnode::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serialnode

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'serialnode': ['/home/yang/serial_catkin_ws/src/serialnode/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serialnode::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serialnode::position_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serialnode::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serialnode::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialnode::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serialnode::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serialnode::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d66668aabc9e40d78e13110532323445";
  }

  static const char* value(const ::serialnode::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd66668aabc9e40d7ULL;
  static const uint64_t static_value2 = 0x8e13110532323445ULL;
};

template<class ContainerAllocator>
struct DataType< ::serialnode::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serialnode/position";
  }

  static const char* value(const ::serialnode::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serialnode::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string x\n\
string y\n\
string t\n\
";
  }

  static const char* value(const ::serialnode::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serialnode::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.t);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serialnode::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serialnode::position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.y);
    s << indent << "t: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.t);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIALNODE_MESSAGE_POSITION_H
